=== WesCook/BacklogBingo/src/schemas/category-list.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"required": ["version", "name", "categories"],
	"properties": {
		"version": { "type": "number" },
		"name": { "type": "string" },
		"description": { "type": "string" },
		"gamerules": {
			"type": "object",
			"properties": {
				"winCondition": {
					"type": "string",
					"enum": ["row-col", "row-col-diag", "blackout"]
				},
				"star": {
					"type": "string",
					"enum": ["wildcard", "free", "disabled"]
				},
				"allowDuplicates": { "type": "boolean" },
				"gridSize": {
					"type": "string",
					"enum": ["small", "medium", "large"]
				},
				"allowSimilar": { "type": "boolean" },
				"seed": { "type": "string" }
			},
			"additionalProperties": false
		},
		"categories": {
			"type": "array",
			"minItems": 9,
			"items": {
				"type": "object",
				"required": ["name"],
				"properties": {
					"name": { "type": "string" },
					"group": { "type": "string" }
				},
				"additionalProperties": false
			}
		}
	},
	"additionalProperties": false
}

=== WesCook/BacklogBingo/public/event-lists/tildes-gaming-2025-nov-form.json
{
	"version": 1,
	"name": "Tildes Backlog Burner - Nov 2025 Form",
	"description": "A list of genres.  Choose games by their form.",
	"categories": [
		{ "name": "2D platformer" },
		{ "name": "3D platformer" },
		{ "name": "Action-adventure" },
		{ "name": "Arcade racing" },
		{ "name": "ARPG" },
		{ "name": "Autobattler" },
		{ "name": "Base building" },
		{ "name": "Battle royale" },
		{ "name": "Beat 'em up" },
		{ "name": "Arena/boomer shooter" },
		{ "name": "Bullet heaven" },
		{ "name": "Bullet hell" },
		{ "name": "Card game" },
		{ "name": "Casual" },
		{ "name": "City builder" },
		{ "name": "Collectathon" },
		{ "name": "Collectible card game" },
		{ "name": "Combat racing" },
		{ "name": "Comedy" },
		{ "name": "Cozy" },
		{ "name": "Creature collector" },
		{ "name": "CRPG" },
		{ "name": "Dating sim" },
		{ "name": "Deckbuilding" },
		{ "name": "Digital tabletop game" },
		{ "name": "Driving/piloting" },
		{ "name": "Dungeon crawler" },
		{ "name": "Educational" },
		{ "name": "Escape room" },
		{ "name": "Experimental" },
		{ "name": "Exploration" },
		{ "name": "Fighting" },
		{ "name": "FPS" },
		{ "name": "God game" },
		{ "name": "Grand strategy/4X" },
		{ "name": "Hack and slash" },
		{ "name": "Hidden object" },
		{ "name": "Horror" },
		{ "name": "Idle/incremental/clicker" },
		{ "name": "Immersive sim" },
		{ "name": "Indoor sports" },
		{ "name": "Interactive fiction" },
		{ "name": "Job simulator" },
		{ "name": "JRPG" },
		{ "name": "Life sim" },
		{ "name": "Logic" },
		{ "name": "Looter shooter" },
		{ "name": "Management" },
		{ "name": "Match 3" },
		{ "name": "Metroidvania/search action" },
		{ "name": "Military/realistic shooter" },
		{ "name": "Mining" },
		{ "name": "Mystery/investigation" },
		{ "name": "On-rails shooter" },
		{ "name": "Parkour" },
		{ "name": "Physics" },
		{ "name": "Point & click adventure" },
		{ "name": "Political sim" },
		{ "name": "Programming" },
		{ "name": "Puzzle" },
		{ "name": "Puzzle platformer" },
		{ "name": "Real-time strategy/tactics" },
		{ "name": "Rhythm" },
		{ "name": "Roguelike" },
		{ "name": "Run and gun" },
		{ "name": "Runner" },
		{ "name": "Sandbox" },
		{ "name": "Score attack" },
		{ "name": "Shoot 'em up" },
		{ "name": "Shop keeper" },
		{ "name": "Sim racing" },
		{ "name": "Soulslike" },
		{ "name": "Stealth" },
		{ "name": "Summer sports" },
		{ "name": "Survival" },
		{ "name": "Survival horror" },
		{ "name": "Tactical RPG" },
		{ "name": "Tactical shooter" },
		{ "name": "Third-person shooter" },
		{ "name": "Time attack" },
		{ "name": "Time management" },
		{ "name": "Top-down shooter" },
		{ "name": "Tower defense" },
		{ "name": "Turn-based strategy/tactics" },
		{ "name": "Twin-stick shooter" },
		{ "name": "Typing" },
		{ "name": "Vehicle sim" },
		{ "name": "Vehicular combat" },
		{ "name": "Visual novel" },
		{ "name": "Walking simulator" },
		{ "name": "Winter sports" },
		{ "name": "Word game" }
	]
}

=== WesCook/BacklogBingo/public/event-lists/tildes-gaming-2025-may-flux.json
{
	"version": 1,
	"name": "Tildes Backlog Burner - May 2025 Flux",
	"description": "A tweaked and updated version of the May 2024 category list.  Now known as Flux.",
	"categories": [
		{ "name": "Nominated for CHOOSE[a GDC Award|a Steam award|The Game Awards|any award]" },
		{ "name": "Has CHOOSE[a female|a non-human|a robot] antagonist", "group": "Characters" },
		{ "name": "Has CHOOSE[a female|a non-human|a robot|a silent|an animal] protagonist", "group": "Characters" },
		{ "name": "Has multiple playable characters", "group": "Characters" },
		{ "name": "Has romanceable characters", "group": "Characters" },
		{ "name": "You can create your own character", "group": "Characters" },
		{ "name": "You control a party of characters", "group": "Characters" },
		{ "name": "A solo-dev project" },
		{ "name": "An updated version (remake, re-release) of an older game" },
		{ "name": "From a studio you haven't heard of before" },
		{ "name": "From now-defunct dev studio" },
		{ "name": "Is open-source" },
		{ "name": "On a platform you don’t normally use" },
		{ "name": "Adaptation of other media type (e.g. board game, movie)" },
		{ "name": "Features a mystery" },
		{ "name": "Focuses on exploration" },
		{ "name": "Focuses on relationships" },
		{ "name": "Has CHOOSE[a first-person|an isometric|a third-person|a top-down] perspective" },
		{ "name": "Has a fishing minigame" },
		{ "name": "Has a lives system" },
		{ "name": "Has a moral choice system" },
		{ "name": "Has a score system" },
		{ "name": "Has a skill tree" },
		{ "name": "Has a time limit" },
		{ "name": "Has both combat and puzzles" },
		{ "name": "Has cards" },
		{ "name": "Has CHOOSE[AI|aliens|cats|creatures|dinosaurs|dogs|robots|zombies]" },
		{ "name": "Has driving" },
		{ "name": "Has permadeath" },
		{ "name": "Has survival mechanics" },
		{ "name": "Is beatable without killing any enemies" },
		{ "name": "Is mostly text-based" },
		{ "name": "Makes you think" },
		{ "name": "Music/rhythm-focused" },
		{ "name": "Randomness determines your fate" },
		{ "name": "Uses a unique control scheme" },
		{ "name": "Uses procedural generation" },
		{ "name": "You can save/pet/care for animals" },
		{ "name": "Came out more than NUMBER[2,10] years ago" },
		{ "name": "Is one of the oldest games you own" },
		{ "name": "Has a campaign longer than NUMBER[5,15] hours", "group": "Game Time" },
		{ "name": "You can complete it in only a few hours", "group": "Game Time" },
		{ "name": "Chosen for you by someone else" },
		{ "name": "Your friend loves it" },
		{ "name": "Has a review score above NUMBER[80,95]", "group": "Review Score" },
		{ "name": "Has a review score below NUMBER[55,70]", "group": "Review Score" },
		{ "name": "From a series you CHOOSE[have|have never] played", "group": "Series" },
		{ "name": "Part of a long-running series", "group": "Series" },
		{ "name": "Part of a trilogy", "group": "Series" },
		{ "name": "Set CHOOSE[in a dungeon|in a fantasy world|in a historical world|in a post-apocalyptic world|in a real world location|indoors|in space|on an island|outdoors|underwater]" },
		{ "name": "Considered a CHOOSE[classic|cult classic|disappointment|hidden gem]" },
		{ "name": "From a different culture or country" },
		{ "name": "Is considered CHOOSE[casual|challenging|cinematic|emotionally resonant|family friendly|grindy|relaxing]" },
		{ "name": "Known for its CHOOSE[art style|composer|difficulty|ending|impact on gaming|legacy|real-world drama|replay value|soundtrack|]" },
		{ "name": "Recommended by someone on Tildes" },
		{ "name": "Released in the year you joined Tildes" },
		{ "name": "Someone else has played it for their Backlog Burner" },
		{ "name": "You heard about it in our weekly gaming topics" },
		{ "name": "CHOOSE[Begins with the first letter of|Same number of letters as] your username", "group": "Title" },
		{ "name": "Has more than 3 words in its title", "group": "Title" },
		{ "name": "Single-word title", "group": "Title" },
		{ "name": "Has CHOOSE[a number|punctuation|“Super”|the letter ‘Q’|the letter ‘X'] in the title", "group": "Title" },
		{ "name": "You chose it based on title alone", "group": "Title" },
		{ "name": "Has a CHOOSE[calm|cartoony|cozy|dark|experimental|fast-paced|feel-good|futuristic|historical|humorous|literary|logical|lonely|minimalistic|modern|moody|philosophical|realistic|satirical|spooky|surreal|unsettling|whimsical] vibe" },
		{ "name": "Owned for more than NUMBER[2,5] years" },
		{ "name": "A modded game" },
		{ "name": "A romhack or total conversion mod" },
		{ "name": "From a genre you don’t normally play" },
		{ "name": "Has great reviews, but not your usual type" },
		{ "name": "It’s already installed" },
		{ "name": "Popular game you never got around to playing" },
		{ "name": "You have to tinker to get it running" },
		{ "name": "You wanted it when you were younger" },
		{ "name": "You're giving it a second chance" }
	]
}

=== WesCook/BacklogBingo/public/event-lists/tests/random.json
{
	"version": 1,
	"name": "Random Numbers",
	"description": "For testing seed determinism",
	"categories": [
		{ "name": "Number 01 generated NUMBER[1,20]" },
		{ "name": "Number 02 generated NUMBER[1,20]" },
		{ "name": "Number 03 generated NUMBER[1,20]" },
		{ "name": "Number 04 generated NUMBER[1,20]" },
		{ "name": "Number 05 generated NUMBER[1,20]" },
		{ "name": "Number 06 generated NUMBER[1,20]" },
		{ "name": "Number 07 generated NUMBER[1,20]" },
		{ "name": "Number 08 generated NUMBER[1,20]" },
		{ "name": "Number 09 generated NUMBER[1,20]" },
		{ "name": "Number 10 generated NUMBER[1,20]" },
		{ "name": "Number 11 generated NUMBER[1,20]" },
		{ "name": "Number 12 generated NUMBER[1,20]" },
		{ "name": "Number 13 generated NUMBER[1,20]" },
		{ "name": "Number 14 generated NUMBER[1,20]" },
		{ "name": "Number 15 generated NUMBER[1,20]" },
		{ "name": "Number 16 generated NUMBER[1,20]" },
		{ "name": "Number 17 generated NUMBER[1,20]" },
		{ "name": "Number 18 generated NUMBER[1,20]" },
		{ "name": "Number 19 generated NUMBER[1,20]" },
		{ "name": "Number 20 generated NUMBER[1,20]" },
		{ "name": "Number 21 generated NUMBER[1,20]" },
		{ "name": "Number 22 generated NUMBER[1,20]" },
		{ "name": "Number 23 generated NUMBER[1,20]" },
		{ "name": "Number 24 generated NUMBER[1,20]" },
		{ "name": "Number 25 generated NUMBER[1,20]" }
	]
}

=== WesCook/BacklogBingo/src/event-lists/free.json
{
	"version": 1,
	"name": "Free",
	"description": "Conquering your backlog, from A to Z.",
	"gamerules": {
		"star": "disabled"
	},
	"categories": [
		{ "name": "A" },
		{ "name": "B" },
		{ "name": "C" },
		{ "name": "D" },
		{ "name": "E" },
		{ "name": "F" },
		{ "name": "G" },
		{ "name": "H" },
		{ "name": "I" },
		{ "name": "J" },
		{ "name": "K" },
		{ "name": "L" },
		{ "name": "M" },
		{ "name": "N" },
		{ "name": "O" },
		{ "name": "P" },
		{ "name": "Q" },
		{ "name": "R" },
		{ "name": "S" },
		{ "name": "T" },
		{ "name": "U" },
		{ "name": "V" },
		{ "name": "W" },
		{ "name": "X" },
		{ "name": "Y" },
		{ "name": "Z" }
	]
}

=== WesCook/BacklogBingo/public/event-lists/tildes-gaming-2025-may-flow.json
{
	"version": 1,
	"name": "Tildes Backlog Burner - May 2025 Flow",
	"description": "A conceptually abstract list of ideas to guide you.  Let your imagination flow.",
	"categories": [
		{ "name": "Absence" },
		{ "name": "Abundance" },
		{ "name": "Adaptation" },
		{ "name": "Aesthetic" },
		{ "name": "Annihilation" },
		{ "name": "Ascent" },
		{ "name": "Balance" },
		{ "name": "Beauty" },
		{ "name": "Belonging" },
		{ "name": "Bizarre" },
		{ "name": "Brief" },
		{ "name": "Bright" },
		{ "name": "Calm" },
		{ "name": "Causality" },
		{ "name": "Change" },
		{ "name": "Chaos" },
		{ "name": "Choice" },
		{ "name": "Collaboration" },
		{ "name": "Color" },
		{ "name": "Comfortable" },
		{ "name": "Community" },
		{ "name": "Complexity" },
		{ "name": "Conflict" },
		{ "name": "Connection" },
		{ "name": "Contemplative" },
		{ "name": "Contrast" },
		{ "name": "Courage" },
		{ "name": "Creativity" },
		{ "name": "Curiosity" },
		{ "name": "Darkness" },
		{ "name": "Deception" },
		{ "name": "Defense" },
		{ "name": "Destruction" },
		{ "name": "Dimension" },
		{ "name": "Discovery" },
		{ "name": "Distribution" },
		{ "name": "Duality" },
		{ "name": "Emergence" },
		{ "name": "Empathy" },
		{ "name": "Endurance" },
		{ "name": "Erosion" },
		{ "name": "Evolution" },
		{ "name": "Expansive" },
		{ "name": "Exploration" },
		{ "name": "Faith" },
		{ "name": "Familiar" },
		{ "name": "Fear" },
		{ "name": "Fight" },
		{ "name": "Flashy" },
		{ "name": "Fleeting" },
		{ "name": "Focus" },
		{ "name": "Fragmentation" },
		{ "name": "Freedom" },
		{ "name": "Frenetic" },
		{ "name": "Friction" },
		{ "name": "Gentle" },
		{ "name": "Gradual" },
		{ "name": "Growth" },
		{ "name": "Happiness" },
		{ "name": "Harmony" },
		{ "name": "Humor" },
		{ "name": "Identity" },
		{ "name": "Increment" },
		{ "name": "Isolation" },
		{ "name": "Justice" },
		{ "name": "Knowledge" },
		{ "name": "Legacy" },
		{ "name": "Light" },
		{ "name": "Lost" },
		{ "name": "Love" },
		{ "name": "Maneuver" },
		{ "name": "Memory" },
		{ "name": "Momentum" },
		{ "name": "Morality" },
		{ "name": "Mystery" },
		{ "name": "Niche" },
		{ "name": "Nostalgia" },
		{ "name": "Open" },
		{ "name": "Order" },
		{ "name": "Organic" },
		{ "name": "Organization" },
		{ "name": "Peace" },
		{ "name": "Perspective" },
		{ "name": "Power" },
		{ "name": "Precision" },
		{ "name": "Pride" },
		{ "name": "Progress" },
		{ "name": "Quantity" },
		{ "name": "Rebirth" },
		{ "name": "Recursion" },
		{ "name": "Reluctance" },
		{ "name": "Repetition" },
		{ "name": "Resistance" },
		{ "name": "Restoration" },
		{ "name": "Silence" },
		{ "name": "Simple" },
		{ "name": "Simplicity" },
		{ "name": "Slow-burn" },
		{ "name": "Sly" },
		{ "name": "Sound" },
		{ "name": "Style" },
		{ "name": "Survival" },
		{ "name": "Swift" },
		{ "name": "Symmetry" },
		{ "name": "Synthesis" },
		{ "name": "Tense" },
		{ "name": "Tension" },
		{ "name": "Threshold" },
		{ "name": "Time" },
		{ "name": "Tradition" },
		{ "name": "Traditional" },
		{ "name": "Transformation" },
		{ "name": "Treasure" },
		{ "name": "Trust" },
		{ "name": "Truth" },
		{ "name": "Uncertainty" },
		{ "name": "Unexpected" },
		{ "name": "Unlock" },
		{ "name": "Unorthodox" },
		{ "name": "Variety" },
		{ "name": "Verticality" },
		{ "name": "Vision" },
		{ "name": "Vulnerability" },
		{ "name": "Whimsy" },
		{ "name": "Wonder" }
	]
}

=== WesCook/BacklogBingo/public/event-lists/tildes-gaming-2024-may.json
{
	"version": 1,
	"name": "Tildes Backlog Burner - May 2024",
	"description": "The first major category overhaul.",
	"categories": [
		{ "name": "Has less than NUMBER[2,20] achievements", "group": "Achievements" },
		{ "name": "Has more than NUMBER[50,100] achievements", "group": "Achievements" },
		{ "name": "Has no achievements", "group": "Achievements" },
		{ "name": "You can't remember where you got it from", "group": "Acquisition" },
		{ "name": "You got from a bundle", "group": "Acquisition" },
		{ "name": "You got it as a gift", "group": "Acquisition" },
		{ "name": "You got it from crowdfunding", "group": "Acquisition" },
		{ "name": "You own it on physical media", "group": "Acquisition" },
		{ "name": "You regret buying it", "group": "Acquisition" },
		{ "name": "Nominated for CHOOSE[a GDC Award|a Steam award|The Game Awards|any award]" },
		{ "name": "Has CHOOSE[a female|a robot|an animal|a non-human] antagonist", "group": "Characters" },
		{ "name": "Has CHOOSE[a female|a robot|an animal|a non-human|a silent] protagonist", "group": "Characters" },
		{ "name": "Has romanceable characters", "group": "Characters" },
		{ "name": "Multiple playable characters", "group": "Characters" },
		{ "name": "You can create your own character", "group": "Characters" },
		{ "name": "You control a party of characters", "group": "Characters" },
		{ "name": "You got it CHOOSE[for free|on sale|at full price]" },
		{ "name": "A solo-dev project" },
		{ "name": "An updated version (remake, re-release) of an older game" },
		{ "name": "From a different country than you" },
		{ "name": "From a studio you haven't heard of before" },
		{ "name": "From now-defunct dev studio" },
		{ "name": "Is open-source" },
		{ "name": "Has been removed from a distribution service", "group": "Distribution" },
		{ "name": "Is considered “abandonware”", "group": "Distribution" },
		{ "name": "Not found on any distribution service", "group": "Distribution" },
		{ "name": "On a platform you don’t normally use", "group": "Distribution" },
		{ "name": "Has CHOOSE[campaign|no|cosmetic|season pass] DLC" },
		{ "name": "Adaptation of other media type (e.g. board game, movie)" },
		{ "name": "Features a mystery" },
		{ "name": "Focuses on exploration" },
		{ "name": "Focuses on relationships" },
		{ "name": "Has a branching storyline" },
		{ "name": "Has a fishing minigame" },
		{ "name": "Has a lives system" },
		{ "name": "Has a moral choice system" },
		{ "name": "Has a skill tree" },
		{ "name": "Has a time limit" },
		{ "name": "Has a weather system" },
		{ "name": "Has both combat and puzzles" },
		{ "name": "Has CHOOSE[aliens|dinosaurs|robots|AI|cats|dogs|zombies]" },
		{ "name": "Has driving" },
		{ "name": "Has gravity manipulation" },
		{ "name": "Has permadeath" },
		{ "name": "Has survival mechanics" },
		{ "name": "Has time manipulation" },
		{ "name": "Has/uses cards" },
		{ "name": "Is beatable without killing any enemies" },
		{ "name": "Is mostly text-based" },
		{ "name": "Light and dark play a role" },
		{ "name": "Music/rhythm-focused" },
		{ "name": "Randomness determines your fate" },
		{ "name": "Uses a unique control scheme" },
		{ "name": "Uses at most three buttons" },
		{ "name": "Uses procedural generation" },
		{ "name": "You can save/pet/care for animals" },
		{ "name": "Came out more than NUMBER[2,10] years ago" },
		{ "name": "Is one of the oldest games you own" },
		{ "name": "Has a campaign longer than NUMBER[5,15] hours", "group": "Game Time" },
		{ "name": "You can complete it in one sitting", "group": "Game Time" },
		{ "name": "You can complete it in only a few hours", "group": "Game Time" },
		{ "name": "Chosen for you by someone else" },
		{ "name": "Recommended by someone IRL" },
		{ "name": "Your friend loves it" },
		{ "name": "Has a review score above NUMBER[80,95]", "group": "Review Score" },
		{ "name": "Has a review score below NUMBER[55,70]", "group": "Review Score" },
		{ "name": "From a series you CHOOSE[have|have never] played", "group": "Series" },
		{ "name": "Part of a long-running series", "group": "Series" },
		{ "name": "Part of a trilogy", "group": "Series" },
		{ "name": "Set CHOOSE[in a post-apocalyptic world|in a real world location|in a fantasy world|in space|in a dungeon|in a historical world|underwater]" },
		{ "name": "Considered a CHOOSE[classic|cult classic|disappointment]" },
		{ "name": "From a different culture or country" },
		{ "name": "Has been banned, censored, or challenged" },
		{ "name": "Known for its CHOOSE[difficulty|soundtrack|composer|art style|ending|replay value|legacy|impact on gaming|real-world drama]" },
		{ "name": "CHOOSE[Begins with the first letter of|Same number of letters as] your username" },
		{ "name": "Recommended by someone on Tildes" },
		{ "name": "Released in the year you joined Tildes" },
		{ "name": "Someone else has played it for their Backlog Burner" },
		{ "name": "You heard about it in our weekly gaming topics" },
		{ "name": "Has CHOOSE[“Super”|a number|punctuation|the letter ‘Q’|the letter ‘X'] in the title" },
		{ "name": "You chose it based on title alone" },
		{ "name": "Has a CHOOSE[feel-good|spooky|moody|humorous|cozy|lonely|relaxing|futuristic|surreal|experimental|philosophical|satirical|unsettling|whimsical] vibe" },
		{ "name": "“When the hell did I buy this?”" },
		{ "name": "Owned for more than NUMBER[2,7] years" },
		{ "name": "A modded game" },
		{ "name": "A romhack or total conversion mod" },
		{ "name": "From a genre you don’t normally play" },
		{ "name": "From a genre you find challenging" },
		{ "name": "Great reviews, but not your usual type" },
		{ "name": "Has environmental storytelling" },
		{ "name": "It’s already installed" },
		{ "name": "Popular game you never got around to playing" },
		{ "name": "Released before you were born" },
		{ "name": "You don't think you'll enjoy it" },
		{ "name": "You have to tinker to get it running" },
		{ "name": "You started it but never completed it" },
		{ "name": "You wanted it when you were younger" },
		{ "name": "You're giving it a second chance" }
	]
}
